FROM node:18-alpine

# Set the working directory and install dependencies
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .

# Build the app
RUN npm run build

# Run the migrations and start the app in production mode
CMD ["./scripts/migrate-and-start.sh"]