version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: CHANGE_DATABASE_USERNAME
      POSTGRES_PASSWORD: CHANGE_DATABASE_PASSWORD
      POSTGRES_DB: CHANGE_PROJECT_NAME:prod
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

volumes:
    postgres-data: