import Provider from '@/components/Provider'
import './globals.css'
import type { Metadata } from 'next'

// The following import prevents a Font Awesome icon server-side rendering bug,
// where the icons flash from a very large icon down to a properly sized one:
import '@fortawesome/fontawesome-svg-core/styles.css';
// Prevent fontawesome from adding its CSS since we did it manually above:
import { config } from '@fortawesome/fontawesome-svg-core';
config.autoAddCss = false; /* eslint-disable import/first */

import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast';
import ResponsiveNavbar from '@/components/layout/ResponsiveNavbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Provider>
                    <Toaster />
                    <ResponsiveNavbar className='' />
                    {children}
                </Provider>
            </body>
        </html>
    )
}
